import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BatteryFull, CheckCircle2, Delete, HelpCircle, Home, Radio, Signal, Smartphone, Volume2 } from 'lucide-react';
import { api, login } from '../services/api';

const MAIN = 'MAIN_MENU';
const demoLogin = async () => { if (localStorage.getItem('farmlink_token')) return; const { data } = await login({ email: 'farmer@farmlink.demo', password: 'farmer123' }); localStorage.setItem('farmlink_token', data.token); localStorage.setItem('farmlink_user', JSON.stringify(data.user)); };
const menuItems = ['Sell Crop', 'Check Crop Price', 'My Listings', 'My Orders', 'Payment Status', 'Request Pickup', 'FPO Hub', 'Exit'];

export default function UssdSimulator() {
  const [state, setState] = useState(MAIN); const [value, setValue] = useState(''); const [form, setForm] = useState({ crop: '', quantity: '', location: '' }); const [data, setData] = useState(null); const [error, setError] = useState(''); const [demoRunning, setDemoRunning] = useState(false);
  useEffect(() => { demoLogin().catch(() => setError('The FarmLink API is unavailable. Start the backend to sync this simulation.')); }, []);
  const resetInput = () => { setValue(''); setError(''); };
  const go = next => { setState(next); resetInput(); setData(null); };
  const back = () => { if (state === MAIN) return; go(MAIN); };
  const showMenu = <div className="ussd-footer"><button onClick={back}><ArrowLeft size={14}/> 1 Back</button><button onClick={() => go(MAIN)}><Home size={14}/> 2 Main menu</button></div>;
  const promptFor = { SELL_CROP_NAME: 'Enter crop name:', SELL_CROP_QUANTITY: 'Enter quantity in kg:', SELL_CROP_LOCATION: 'Enter village:', PRICE_LOOKUP: 'Enter crop name:', PRICE_LOCATION: 'Enter village:' }[state];
  const submitValue = async () => {
    const input = value.trim(); if (!input) return;
    if (state === 'SELL_CROP_NAME') { setForm(current => ({ ...current, crop: input })); setValue(''); setState('SELL_CROP_QUANTITY'); return; }
    if (state === 'SELL_CROP_QUANTITY') { if (!/^\d+(\.\d+)?$/.test(input)) { setError('Enter a number, for example 500.'); return; } setForm(current => ({ ...current, quantity: input })); setValue(''); setState('SELL_CROP_LOCATION'); return; }
    if (state === 'SELL_CROP_LOCATION') { setForm(current => ({ ...current, location: input })); setValue(''); setState('SELL_CROP_CONFIRM'); return; }
    if (state === 'PRICE_LOOKUP') { setForm(current => ({ ...current, crop: input })); setValue(''); setState('PRICE_LOCATION'); return; }
    if (state === 'PRICE_LOCATION') { try { const response = await api.get('/ai/price', { params: { crop: form.crop, location: input, quality: 'Grade A' } }); setData(response.data); setState('PRICE_RESULT'); resetInput(); } catch { setError('Could not reach the prototype AI service.'); } }
  };
  const confirmListing = async (listingForm = form) => { try { const response = await api.post('/listings', { crop: listingForm.crop, quantity: Number(listingForm.quantity), unit: 'kg', location: listingForm.location, source: 'USSD', quality: 'Grade A' }); setData(response.data); setState('LISTING_CREATED'); } catch (err) { setError(err.response?.data?.error || 'Listing could not be created.'); } };
  const loadData = async next => { try { const response = await api.get(next === 'MY_LISTINGS' ? '/listings' : next === 'MY_ORDERS' ? '/orders' : next === 'FPO_INFO' ? '/fpo/dashboard' : '/payments/status'); setData(response.data); setState(next); } catch { setError('Could not retrieve FarmLink data.'); } };
  const requestPickup = async () => { try { const response = await api.post('/pickup-requests', { orderId: 'ORD-FL-00128', crop: 'Tomato', quantity: 500, pickupAddress: 'Ravi Organic Farm, Melur', preferredDate: '2026-09-23', preferredTime: '10:00', source: 'USSD' }); setData(response.data.pickupRequest); setState('PICKUP_CREATED'); } catch (err) { setError(err.response?.data?.error || 'Could not submit pickup request.'); } };
  const select = key => { if (state === MAIN) { const actions = { 1: () => go('SELL_CROP_NAME'), 2: () => go('PRICE_LOOKUP'), 3: () => loadData('MY_LISTINGS'), 4: () => loadData('MY_ORDERS'), 5: () => loadData('PAYMENT_STATUS'), 6: requestPickup, 7: () => loadData('FPO_INFO'), 8: () => go('EXIT') }; actions[key]?.(); } else if (state === 'SELL_CROP_CONFIRM') { if (key === 1) confirmListing(); if (key === 2) go('SELL_CROP_NAME'); if (key === 3) go(MAIN); } else if (state === 'PRICE_RESULT' && key === 1) go('SELL_CROP_NAME'); else if (['MY_LISTINGS', 'MY_ORDERS', 'PAYMENT_STATUS', 'FPO_INFO', 'HELP', 'LISTING_CREATED', 'PICKUP_CREATED'].includes(state) && key === 1) go(MAIN); };
  useEffect(() => { const onKeyDown = event => { if (event.target instanceof HTMLInputElement) return; if (/^[0-9]$/.test(event.key)) select(Number(event.key)); }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown); });
  const runDemo = () => { const demoForm = { crop: 'Tomato', quantity: '500', location: 'Melur' }; setDemoRunning(true); setState('SELL_CROP_CONFIRM'); setForm(demoForm); setData(null); setTimeout(() => confirmListing(demoForm).finally(() => setDemoRunning(false)), 900); };
  const renderScreen = () => {
    if (state === MAIN) return <><div className="ussd-brand">FARMLINK <span>*123#</span></div><div className="ussd-title">USSD + IVR<br/>Prototype Simulation</div><p className="ussd-copy">Basic Phone Access Simulation</p>{menuItems.map((item, index) => <button className="ussd-menu-item" key={item} onClick={() => select(index + 1)}><b>{index + 1}</b>{item}</button>)}<p className="ussd-note">Production deployment would connect this flow to a telecom USSD gateway.</p></>;
    if (['SELL_CROP_NAME', 'SELL_CROP_QUANTITY', 'SELL_CROP_LOCATION', 'PRICE_LOOKUP', 'PRICE_LOCATION'].includes(state)) return <><div className="ussd-step">{state.startsWith('PRICE') ? 'CHECK CROP PRICE' : 'SELL CROP'}</div><h3>{promptFor}</h3><input autoFocus className="ussd-input" value={value} onChange={event => setValue(event.target.value)} onKeyDown={event => event.key === 'Enter' && submitValue()} placeholder={state.includes('QUANTITY') ? '500' : 'Type here'}/>{error && <div className="ussd-error">{error}</div>}<button className="ussd-submit" onClick={submitValue}>Send</button>{showMenu}</>;
    if (state === 'SELL_CROP_CONFIRM') return <><div className="ussd-step">CONFIRM LISTING</div><div className="ussd-confirm"><span>Crop</span><strong>{form.crop}</strong><span>Quantity</span><strong>{form.quantity} kg</strong><span>Village</span><strong>{form.location}</strong></div><button className="ussd-menu-item" onClick={() => select(1)}><b>1</b>Confirm</button><button className="ussd-menu-item" onClick={() => select(2)}><b>2</b>Edit</button><button className="ussd-menu-item" onClick={() => select(3)}><b>3</b>Cancel</button>{showMenu}</>;
    if (state === 'LISTING_CREATED') return <><CheckCircle2 className="ussd-success-icon"/><h3>Listing created</h3><p className="ussd-copy">{form.quantity} kg of {form.crop} from {form.location} is now in FarmLink.</p><div className="ussd-result">Prototype AI estimate<br/><strong>₹{data?.price?.predicted_price || 27}/kg</strong><br/>Buyer match: {data?.matches?.[0]?.score || 94}%</div><button className="ussd-menu-item" onClick={() => go(MAIN)}><b>1</b>Main menu</button></>;
    if (state === 'PICKUP_CREATED') return <><CheckCircle2 className="ussd-success-icon"/><h3>Pickup requested</h3><p className="ussd-copy">{data?.id} submitted to Melur Farmer Hub.</p><div className="ussd-result">Tomato • 500 kg<br/>Status: <strong>REQUESTED</strong><br/>Next: Vehicle assignment</div><button className="ussd-menu-item" onClick={() => go(MAIN)}><b>1</b>Main menu</button></>;
    if (state === 'PRICE_RESULT') return <><div className="ussd-step">PROTOTYPE AI ESTIMATE</div><h3>{form.crop}<br/><small>Melur</small></h3><div className="ussd-result">Reference Price<br/><strong>₹{data?.reference_price}/kg</strong><br/><br/>FarmLink AI Estimate<br/><strong>₹{data?.predicted_price}/kg</strong><br/>Confidence: {data?.confidence}%</div><button className="ussd-menu-item" onClick={() => select(1)}><b>1</b>List crop</button>{showMenu}</>;
    if (state === 'MY_LISTINGS') return <><div className="ussd-step">MY LISTINGS</div>{(data?.listings || []).slice(0, 4).map((item, index) => <div className="ussd-list-row" key={item.id}><b>{index + 1}</b><span>{item.crop} - {item.quantity} {item.unit}<small>{item.status || 'AVAILABLE'} • ₹{item.price}/kg</small></span></div>)}{showMenu}</>;
    if (state === 'MY_ORDERS') return <><div className="ussd-step">MY ORDERS</div>{(data?.orders || []).slice(0, 3).map((item, index) => <div className="ussd-list-row" key={item.id}><b>{index + 1}</b><span>{item.crop} - {item.quantity} kg<small>Status: {item.status}</small></span></div>)}{showMenu}</>;
    if (state === 'PAYMENT_STATUS') return <><div className="ussd-step">DEMO SETTLEMENT</div><div className="ussd-result">Order: {data?.orderId || 'ORD-FL-00128'}<br/>Amount: <strong>₹{data?.amount || 14000}</strong><br/><br/>Status: SETTLED<br/>Farmer Share: ₹11,000<br/>FPO: ₹700<br/>Transport: ₹1,300<br/>Platform: ₹1,000</div><p className="ussd-warning">Demo Settlement<br/>No real money transferred</p>{showMenu}</>;
    if (state === 'FPO_INFO') return <><div className="ussd-step">FPO HUB</div><h3>Melur Farmer Hub</h3><div className="ussd-result">Nearby Farmers: 12<br/>Aggregated Produce: {data?.incomingCrop || 1240} kg<br/>Today's Pickup: {data?.hubInventory || 530} kg<br/>Next Pickup: Tomorrow 10:00 AM</div>{showMenu}</>;
    if (state === 'HELP') return <><div className="ussd-step">FARMLINK SUPPORT</div>{['Sell Crop', 'Check Price', 'Check Orders', 'Payment Status', 'FPO Information', 'Main Menu'].map((item, index) => <div className="ussd-help-row" key={item}><b>{index + 1}</b>{item}</div>)}{showMenu}</>;
    return <><Radio className="ussd-success-icon"/><h3>Session ended</h3><p className="ussd-copy">Thank you for using FarmLink.</p><button className="ussd-submit" onClick={() => go(MAIN)}>Start again</button></>;
  };
  const keypad = useMemo(() => ['1','2','3','4','5','6','7','8','9','*','0','#'], []);
  return <main className="page simulator-page"><div className="simulator-heading"><div><div className="section-kicker">Inclusive access</div><h1>FarmLink on any phone.</h1><p>Explore the same FarmLink backend through a basic-phone interaction.</p></div><button className="button primary" onClick={runDemo} disabled={demoRunning}><Smartphone size={16}/> {demoRunning ? 'Running demo...' : 'Run Demo Flow'}</button></div><div className="simulator-grid"><section className="phone-shell ussd-phone"><div className="phone-status"><span>FarmLink SIM</span><span><Signal size={12}/> 4G <BatteryFull size={14}/></span></div><div className="phone-screen">{renderScreen()}</div><div className="phone-keypad">{keypad.map(key => <button key={key} onClick={() => { if (state === MAIN || state === 'SELL_CROP_CONFIRM' || state === 'PRICE_RESULT' || ['MY_LISTINGS','MY_ORDERS','PAYMENT_STATUS','FPO_INFO','HELP','LISTING_CREATED'].includes(state)) select(Number(key)); else setValue(current => current + (key === '*' || key === '#' ? '' : key)); }}>{key}</button>)}</div></section><aside className="architecture-panel"><div className="section-kicker">Production architecture</div><h2>Basic phone to trusted trade.</h2><div className="architecture-flow"><span>Basic Phone</span><b>↓</b><span>Telecom USSD Gateway</span><b>↓</b><span>FarmLink Backend</span><b>↓</b><span>PostgreSQL</span><b>↓</b><span>AI / FPO / Buyer / Logistics</span></div><div className="prototype-boundary"><HelpCircle size={16}/><div><strong>USSD + IVR Prototype Simulation</strong><p>Production deployment would connect this flow to a telecom USSD gateway. This browser simulates the basic-phone experience.</p></div></div></aside></div></main>;
}
