import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { Pool } from 'pg';

const app = express();
const port = process.env.PORT || 5000;
const secret = process.env.JWT_SECRET || 'farmlink-local-demo-secret';
const corsOrigins = (process.env.CORS_ORIGIN || 'https://farmlink-sih.vercel.app,http://localhost:5173,http://localhost:5174').split(',').map(origin => origin.trim()).filter(Boolean);
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: (origin, callback) => { if (!origin || corsOrigins.includes(origin)) return callback(null, true); return callback(new Error('Origin is not allowed by CORS')); }, credentials: true }));
app.use(express.json());
app.use(rateLimit({ windowMs: 60_000, limit: 120, standardHeaders: true, legacyHeaders: false }));

const users = [
  { id: 'usr-ravi', name: 'Ravi Kumar', email: 'farmer@farmlink.demo', role: 'FARMER', password: 'farmer123', fpo: 'Melur Farmer Hub' },
  { id: 'usr-meera', name: 'Meera Iyer', email: 'consumer@farmlink.demo', role: 'CONSUMER', password: 'consumer123' },
  { id: 'usr-chennai', name: 'Chennai Fresh Foods', email: 'buyer@farmlink.demo', role: 'BULK_BUYER', password: 'buyer123' },
  { id: 'usr-fpo', name: 'Melur Farmer Hub', email: 'fpo@farmlink.demo', role: 'FPO_ADMIN', password: 'fpo123' },
  { id: 'usr-admin', name: 'FarmLink Admin', email: 'admin@farmlink.demo', role: 'ADMIN', password: 'admin123' }
];
const crops = ['Tomato', 'Onion', 'Banana', 'Brinjal', 'Okra', 'Mango', 'Paddy', 'Groundnut', 'Chilli', 'Coconut'];
const listings = [
  { id: 'lot-ravi-tomato', crop: 'Tomato', variety: 'Namdhari', farmer: 'Ravi Kumar', farm: 'Ravi Organic Farm', fpo: 'Melur Farmer Hub', location: 'Melur, Madurai', quantity: 500, unit: 'kg', quality: 'Grade A', price: 35, harvestDate: '2026-09-24', status: 'ACTIVE' },
  { id: 'lot-kavya-onion', crop: 'Onion', variety: 'Small Red', farmer: 'Kavya Farms', farm: 'Kavya Agro', fpo: 'Madurai Growers FPO', location: 'Thirumangalam, Madurai', quantity: 800, unit: 'kg', quality: 'Grade A', price: 29, harvestDate: '2026-09-26', status: 'ACTIVE' },
  { id: 'lot-arun-banana', crop: 'Banana', variety: 'Nendran', farmer: 'Arun Selvam', farm: 'Vaigai Fields', fpo: 'Vaigai Valley FPO', location: 'Dindigul, Tamil Nadu', quantity: 300, unit: 'kg', quality: 'Grade A', price: 42, harvestDate: '2026-09-25', status: 'ACTIVE' },
  { id: 'lot-selvi-okra', crop: 'Okra', variety: 'Hybrid', farmer: 'Selvi M', farm: 'Green Bend Farm', fpo: 'Melur Farmer Hub', location: 'Melur, Madurai', quantity: 180, unit: 'kg', quality: 'Grade B', price: 38, harvestDate: '2026-09-23', status: 'ACTIVE' }
];
const orders = [{ id: 'ORD-FL-00128', listingId: 'lot-ravi-tomato', crop: 'Tomato', quantity: 400, total: 14000, buyer: 'Chennai Fresh Foods', farmer: 'Ravi Kumar', status: 'IN_TRANSIT', createdAt: '2026-09-21T09:30:00Z' }];
const vehicles = [{ id: 'veh-murugan', registration: 'TN-58-AB-1234', transporter: 'Murugan Logistics', transporterId: 'trans-murugan', capacity: 600, currentLoad: 0, status: 'AVAILABLE' }, { id: 'veh-arun', registration: 'TN-59-CD-4567', transporter: 'Arun Logistics', transporterId: 'trans-arun', capacity: 1000, currentLoad: 700, status: 'AVAILABLE' }];
const pickupRequests = [{ id: 'PR-10021', orderId: 'ORD-FL-00128', farmer: 'Ravi Kumar', farmerId: 'usr-ravi', crop: 'Tomato', quantity: 500, fpo: 'Melur Farmer Hub', buyer: 'Chennai Fresh Foods', pickupAddress: 'Ravi Organic Farm, Melur', preferredDate: '2026-09-23', preferredTime: '10:00', specialInstructions: '', status: 'REQUESTED', vehicle: null, transporter: null, routeId: null, createdAt: '2026-09-22T09:00:00Z', updatedAt: '2026-09-22T09:00:00Z' }];
const notifications = [{ id: 'n1', text: 'Your tomato lot has been matched with Chennai Fresh Foods.', audience: 'FARMER', read: false }, { id: 'n2', text: '530 kg tomato cluster is ready for pickup.', audience: 'FPO_ADMIN', read: false }, { id: 'n3', text: 'Demo settlement completed.', audience: 'ALL', read: false }];
const ledger = [{ id: 'TXN-FL-2026-00128', orderId: 'ORD-FL-00128', amount: 14000, farmer: 'Ravi Kumar', buyer: 'Chennai Fresh Foods', hash: '0x8b7d4e2a91f6c3d0a1142c58e7bd04fa', status: 'VERIFIED', simulated: true, createdAt: '2026-09-21T12:15:00Z' }];
let pool;
try { if (process.env.DATABASE_URL) pool = new Pool({ connectionString: process.env.DATABASE_URL }); } catch { pool = null; }
const auth = (req, res, next) => { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.status(401).json({ error: 'Authentication required' }); try { req.user = jwt.verify(token, secret); next(); } catch { res.status(401).json({ error: 'Invalid token' }); } };
const tokenFor = user => jwt.sign({ id: user.id, name: user.name, role: user.role, email: user.email }, secret, { expiresIn: '8h' });
const aiPrice = input => { const base = { Tomato: 24, Onion: 22, Banana: 36, Brinjal: 30, Okra: 32, Mango: 55 }[input.crop] || 25; const quality = input.quality === 'Grade A' ? 3 : 0; const predicted = base + quality; return { reference_price: base, predicted_price: predicted, confidence: 87, factors: ['Historical seeded prices', 'Prototype demand signal', 'Quantity and location', 'Season and quality'] }; };
const routeStops = [
  { name: 'Ravi Kumar', subtitle: 'Ravi Organic Farm', type: 'farmer', lat: 10.028, lng: 78.337, quantity: 150 },
  { name: 'Kavya Farms', subtitle: 'Kavya Agro', type: 'farmer', lat: 10.003, lng: 78.301, quantity: 200 },
  { name: 'Arun Selvam', subtitle: 'Vaigai Fields', type: 'farmer', lat: 10.058, lng: 78.365, quantity: 180 },
  { name: 'Melur Farmer Hub', subtitle: 'FPO Micro-Hub', type: 'fpo', lat: 10.032, lng: 78.342, quantity: 530 },
  { name: 'Chennai Fresh Foods', subtitle: 'Bulk Buyer', type: 'buyer', lat: 10.071, lng: 78.389, quantity: 0 }
];
const haversine = (from, to) => { const radius = 6371; const lat = (to.lat - from.lat) * Math.PI / 180; const lng = (to.lng - from.lng) * Math.PI / 180; const a = Math.sin(lat / 2) ** 2 + Math.cos(from.lat * Math.PI / 180) * Math.cos(to.lat * Math.PI / 180) * Math.sin(lng / 2) ** 2; return radius * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); };
const localRoute = stops => { const distance = stops.slice(1).reduce((sum, stop, index) => sum + haversine(stops[index], stop), 0); return { distance: Number(distance.toFixed(1)), duration: Math.round(distance * 2.2), mode: 'Demo Route - Routing service unavailable' }; };
const pickupTransitions = { REQUESTED: ['FPO_ACCEPTED', 'CANCELLED'], FPO_ACCEPTED: ['VEHICLE_ASSIGNED', 'CANCELLED'], VEHICLE_ASSIGNED: ['PICKUP_SCHEDULED', 'CANCELLED'], PICKUP_SCHEDULED: ['PICKED_UP', 'CANCELLED'], PICKED_UP: ['IN_TRANSIT'], IN_TRANSIT: ['DELIVERED'], DELIVERED: [], CANCELLED: [] };
const pickupId = () => `PR-${String(10021 + pickupRequests.length).padStart(5, '0')}`;
app.get('/api/health', (req, res) => res.json({ ok: true, status: 'ok', service: 'farmlink-backend', mode: 'Prototype Demo' }));
app.post('/api/auth/login', (req, res) => { const result = z.object({ email: z.string().email(), password: z.string().min(1) }).safeParse(req.body); if (!result.success) return res.status(400).json({ error: 'Valid email and password are required' }); const user = users.find(item => item.email === result.data.email && item.password === result.data.password); if (!user) return res.status(401).json({ error: 'Invalid demo credentials' }); const { password, ...safe } = user; res.json({ token: tokenFor(user), user: safe }); });
app.post('/api/auth/register', (req, res) => { const result = z.object({ name: z.string().min(2), email: z.string().email(), password: z.string().min(6), role: z.enum(['FARMER', 'CONSUMER', 'BULK_BUYER']).default('CONSUMER') }).safeParse(req.body); if (!result.success) return res.status(400).json({ error: 'Please check registration fields' }); const user = { id: `usr-${Date.now()}`, ...result.data }; users.push(user); res.status(201).json({ token: tokenFor(user), user }); });
app.get('/api/auth/me', auth, (req, res) => res.json({ user: users.find(user => user.id === req.user.id) || req.user }));
app.get('/api/listings', (req, res) => { let result = listings; if (req.query.crop) result = result.filter(item => item.crop.toLowerCase() === String(req.query.crop).toLowerCase()); res.json({ listings: result, meta: { demo: true, total: result.length } }); });
app.get('/api/listings/:id', (req, res) => { const item = listings.find(listing => listing.id === req.params.id); item ? res.json(item) : res.status(404).json({ error: 'Listing not found' }); });
app.post('/api/listings', auth, (req, res) => { const result = z.object({ crop: z.string().min(2), quantity: z.coerce.number().positive(), unit: z.string().default('kg'), quality: z.string().default('Grade A'), harvestDate: z.string().optional(), location: z.string().default('Melur, Madurai'), variety: z.string().default('Local'), source: z.enum(['WEB', 'VOICE', 'USSD', 'IVR']).default('WEB') }).safeParse(req.body); if (!result.success) return res.status(400).json({ error: 'Crop and positive quantity are required' }); const listing = { id: `lot-${Date.now()}`, ...result.data, farmer: req.user.name, farm: 'Ravi Organic Farm', fpo: 'Melur Farmer Hub', price: aiPrice(result.data).predicted_price, status: 'ACTIVE' }; listings.unshift(listing); res.status(201).json({ listing, price: aiPrice(result.data), matches: [{ name: 'Chennai Fresh Foods', score: 94, distance: '18 km', offer: 28 }, { name: 'Melur Retail Hub', score: 87, distance: '6 km', offer: 26 }] }); });
app.post('/api/listings/voice', auth, (req, res) => { const result = z.object({ transcript: z.string().min(1), crop: z.string().min(2), quantity: z.coerce.number().positive(), unit: z.enum(['kg', 'ton', 'quintal']).default('kg'), available_from: z.string().optional() }).safeParse(req.body); if (!result.success) return res.status(400).json({ error: 'Please confirm a valid crop, quantity, and unit.' }); const priceInput = { ...result.data, quality: 'Grade A' }; const listing = { id: `lot-${Date.now()}`, crop: result.data.crop, quantity: result.data.quantity, unit: result.data.unit, available_from: result.data.available_from, farmer: req.user.name, farm: 'Ravi Organic Farm', fpo: 'Melur Farmer Hub', location: 'Melur, Madurai', price: aiPrice(priceInput).predicted_price, status: 'ACTIVE', source: 'VOICE' }; listings.unshift(listing); res.status(201).json({ listing, price: aiPrice(priceInput), matches: [{ name: 'Chennai Fresh Foods', score: 94, distance: '18 km', offer: 28 }, { name: 'Melur Retail Hub', score: 87, distance: '6 km', offer: 26 }] }); });
app.post('/api/pickup-requests', auth, (req, res) => { const result = z.object({ orderId: z.string().min(3), crop: z.string().min(2).default('Tomato'), quantity: z.coerce.number().positive(), pickupAddress: z.string().min(2), preferredDate: z.string().min(8), preferredTime: z.string().min(3), specialInstructions: z.string().optional(), pickupLatitude: z.coerce.number().optional(), pickupLongitude: z.coerce.number().optional() }).safeParse(req.body); if (!result.success) return res.status(400).json({ error: 'Order, quantity, pickup address, date, and time are required.' }); const order = orders.find(item => item.id === result.data.orderId); if (!order) return res.status(404).json({ error: 'Order not found.' }); const request = { id: pickupId(), ...result.data, farmer: req.user.name, farmerId: req.user.id, fpo: 'Melur Farmer Hub', buyer: order.buyer, status: 'REQUESTED', vehicle: null, transporter: null, routeId: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; pickupRequests.unshift(request); res.status(201).json({ pickupRequest: request, notification: `Pickup request ${request.id} submitted.` }); });
app.get('/api/pickup-requests', auth, (req, res) => { const result = req.user.role === 'FPO_ADMIN' || req.user.role === 'ADMIN' ? pickupRequests : pickupRequests.filter(item => item.farmerId === req.user.id); res.json({ pickupRequests: result }); });
app.get('/api/pickup-requests/:id', auth, (req, res) => { const request = pickupRequests.find(item => item.id === req.params.id); if (!request) return res.status(404).json({ error: 'Pickup request not found.' }); if (req.user.role === 'FARMER' && request.farmerId !== req.user.id) return res.status(403).json({ error: 'You can only view your own pickup requests.' }); res.json({ pickupRequest: request }); });
app.get('/api/farmers/:id/pickup-requests', auth, (req, res) => res.json({ pickupRequests: pickupRequests.filter(item => item.farmerId === req.params.id || item.farmerId === req.user.id) }));
app.get('/api/fpo/pickup-requests', auth, (req, res) => res.json({ pickupRequests, vehicles: vehicles.filter(item => item.status === 'AVAILABLE' && item.capacity - item.currentLoad >= 0) }));
app.put('/api/pickup-requests/:id/status', auth, (req, res) => { const request = pickupRequests.find(item => item.id === req.params.id); if (!request) return res.status(404).json({ error: 'Pickup request not found.' }); const nextStatus = req.body.status; if (!pickupTransitions[request.status]?.includes(nextStatus)) return res.status(400).json({ error: `Invalid transition from ${request.status} to ${nextStatus}.` }); request.status = nextStatus; request.updatedAt = new Date().toISOString(); if (nextStatus === 'DELIVERED') { const order = orders.find(item => item.id === request.orderId); if (order) order.status = 'DELIVERED'; } res.json({ pickupRequest: request }); });
app.put('/api/pickup-requests/:id/assign', auth, (req, res) => { const request = pickupRequests.find(item => item.id === req.params.id); const vehicle = vehicles.find(item => item.id === req.body.vehicleId && item.capacity - item.currentLoad >= request?.quantity); if (!request) return res.status(404).json({ error: 'Pickup request not found.' }); if (!vehicle) return res.status(400).json({ error: 'Vehicle not found or insufficient remaining capacity.' }); if (!pickupTransitions[request.status]?.includes('VEHICLE_ASSIGNED')) return res.status(400).json({ error: `Request must be FPO accepted before assignment.` }); request.vehicle = vehicle.registration; request.vehicleId = vehicle.id; request.transporter = vehicle.transporter; request.transporterId = vehicle.transporterId; request.status = 'VEHICLE_ASSIGNED'; request.updatedAt = new Date().toISOString(); res.json({ pickupRequest: request }); });
app.get('/api/orders', auth, (req, res) => res.json({ orders }));
app.get('/api/orders/:id', auth, (req, res) => { const order = orders.find(item => item.id === req.params.id); order ? res.json(order) : res.status(404).json({ error: 'Order not found' }); });
app.post('/api/orders', auth, (req, res) => { const listing = listings.find(item => item.id === req.body.listingId) || listings[0]; const order = { id: `ORD-FL-${String(orders.length + 129).padStart(5, '0')}`, listingId: listing.id, crop: listing.crop, quantity: Number(req.body.quantity || listing.quantity), total: Number(req.body.quantity || listing.quantity) * listing.price, buyer: req.user.name, farmer: listing.farmer, status: 'PENDING', createdAt: new Date().toISOString() }; orders.unshift(order); res.status(201).json(order); });
app.put('/api/orders/:id/status', auth, (req, res) => { const order = orders.find(item => item.id === req.params.id); if (!order) return res.status(404).json({ error: 'Order not found' }); order.status = req.body.status; res.json(order); });
app.get('/api/ai/price', (req, res) => res.json(aiPrice(req.query)));
app.post('/api/ai/price', (req, res) => res.json({ ...aiPrice(req.body), model: 'Prototype Model' }));
app.post('/api/ai/match', (req, res) => res.json({ matches: [{ name: 'Chennai Fresh Foods', score: 94, distance: '18 km', required: 400, offer: 28 }, { name: 'Melur Retail Hub', score: 87, distance: '6 km', required: 250, offer: 26 }, { name: 'Consumer Cluster', score: 81, distance: '12 km', required: 100, offer: 25 }], model: 'Prototype Matching Simulation' }));
app.post('/api/ai/forecast', (req, res) => res.json({ crop: req.body.crop || 'Tomato', forecast: [1,2,3,4,5,6,7].map((day, i) => ({ date: `Day ${day}`, demand: 420 + i * 18, supply: 360 + i * 8 })), model: 'Prototype Forecast' }));
app.get('/api/fpo/dashboard', auth, (req, res) => res.json({ farmers: 42, incomingCrop: 1260, hubInventory: 530, pendingPickups: 3, buyerOrders: 18, role: 'Trust Anchor + Aggregation + Logistics Hub' }));
app.get('/api/fpo/hub', auth, (req, res) => res.json({ lots: [{ farmer: 'Ravi Kumar', quantity: 150 }, { farmer: 'Kavya Farms', quantity: 200 }, { farmer: 'Arun Selvam', quantity: 180 }], total: 530, vehicleCapacity: 600, utilization: 88.3 }));
app.get('/api/routes', auth, (req, res) => res.json({ routes: [{ id: 'route-01', label: 'Melur pooled tomato route', distance: '42 km', time: '1h 35m', utilization: 88.3, cost: 1300, mode: 'Demo Route' }] }));
app.post('/api/routes/optimize', auth, async (req, res) => { const requestedStops = Array.isArray(req.body.stops) && req.body.stops.length > 1 ? req.body.stops : routeStops; const stops = requestedStops.filter(stop => Number.isFinite(Number(stop.lat)) && Number.isFinite(Number(stop.lng))).map(stop => ({ ...stop, lat: Number(stop.lat), lng: Number(stop.lng) })); if (stops.length < 2) return res.status(400).json({ error: 'At least two valid route stops are required.' }); let route = localRoute(stops); const coordinates = stops.map(stop => `${stop.lng},${stop.lat}`).join(';'); try { const response = await fetch(`https://router.project-osrm.org/route/v1/driving/${coordinates}?overview=false`); if (response.ok) { const data = await response.json(); if (data.routes?.[0]) route = { distance: Number((data.routes[0].distance / 1000).toFixed(1)), duration: Math.round(data.routes[0].duration / 60), mode: 'OSRM route' }; } } catch { /* deterministic local fallback remains the demo route */ } const load = stops.reduce((sum, stop) => sum + (stop.type === 'farmer' ? Number(stop.quantity || 0) : 0), 0) || stops.reduce((sum, stop) => sum + Number(stop.quantity || 0), 0); const capacity = Number(req.body.capacity || 600); res.status(201).json({ id: 'route-demo-02', label: 'Optimized pooled route', stops, distance: `${route.distance} km`, duration: `${route.duration} min`, time: `${Math.floor(route.duration / 60)}h ${route.duration % 60}m`, load, capacity, utilization: Number((load / capacity * 100).toFixed(1)), saving: 2100, mode: route.mode, prototype: true }); });
app.post('/api/routes/pool', auth, (req, res) => { const ids = Array.isArray(req.body.pickupRequestIds) ? req.body.pickupRequestIds : []; const selected = pickupRequests.filter(item => ids.includes(item.id)); if (!selected.length) return res.status(400).json({ error: 'Select at least one pickup request.' }); const vehicle = vehicles.find(item => item.id === req.body.vehicleId); const load = selected.reduce((sum, item) => sum + Number(item.quantity), 0); if (!vehicle || vehicle.capacity - vehicle.currentLoad < load) return res.status(400).json({ error: 'Vehicle capacity is insufficient for this pooled route.' }); const routeId = `RT-${1005 + selected.length}`; selected.forEach(item => { item.routeId = routeId; item.status = 'PICKUP_SCHEDULED'; item.updatedAt = new Date().toISOString(); }); res.status(201).json({ route: { id: routeId, vehicle: vehicle.registration, transporter: vehicle.transporter, load, capacity: vehicle.capacity, utilization: Number((load / vehicle.capacity * 100).toFixed(1)), stops: selected.length + 2, mode: 'Prototype pooled route' }, pickupRequests: selected }); });
app.post('/api/payments/demo', auth, (req, res) => { const order = orders.find(item => item.id === req.body.orderId) || orders[0]; const record = { id: `PAY-${Date.now()}`, orderId: order.id, status: 'SUCCESS', simulated: true, total: order.total, splits: { farmer: 11000, fpo: 700, transport: 1300, platform: 1000 }, message: 'Demo Payment - No Real Money Transferred' }; res.status(201).json(record); });
app.get('/api/payments/status', auth, (req, res) => res.json({ orderId: orders[0].id, amount: orders[0].total, status: 'SETTLED', simulated: true, splits: { farmer: 11000, fpo: 700, transport: 1300, platform: 1000 }, message: 'Demo Settlement - No Real Money Transferred' }));
app.get('/api/ledger', auth, (req, res) => res.json({ transactions: ledger }));
app.get('/api/ledger/:id/verify', auth, (req, res) => res.json({ verified: true, message: 'Transaction verified against FarmLink ledger.', simulated: true }));
app.get('/api/notifications', auth, (req, res) => res.json({ notifications }));
app.get('/api/analytics/dashboard', auth, (req, res) => res.json({ metrics: { farmers: 128, fpos: 3, activeListings: listings.length, orders: 15, transactionValue: 284500, farmerPrice: 27, consumerSavings: 12, utilization: 88 }, series: [30, 42, 38, 55, 62, 70, 82] }));
app.get('/api/buyers', (req, res) => res.json({ buyers: [{ name: 'Chennai Fresh Foods', location: 'Chennai', requirement: 'Tomato, 400 kg' }, { name: 'Melur Retail Hub', location: 'Madurai', requirement: 'Mixed vegetables, 250 kg' }] }));
app.use((err, req, res, next) => { console.error(err); res.status(500).json({ error: 'Unexpected server error' }); });
app.listen(port, '0.0.0.0', () => console.log(`FarmLink API listening on 0.0.0.0:${port} (${process.env.DEMO_MODE !== 'false' ? 'demo mode' : 'database mode'})`));
